### ISSUE TITLE
Feature Request: Improved AWS CloudWatch metrics for background job worker pods (from CloudWatch agent)

### ISSUE THREAD

**Issue by ndbroadbent** [convox/convox#866]
I'm building CloudWatch dashboards, and I can see a `service_number_of_running_pods` metric under ContainerInsights. I also have `namespace_number_of_running_pods` metrics, but that includes all services for my app (both web and worker pods).

There's no metrics based on "deployments":

<img width="1441" alt="Image" src="https://github.com/user-attachments/assets/7fdb9d9f-c8ee-4b7f-8d8f-407cf9944d77" />

From AI:

> Container Insights groups pods by service, so without a service—even if deployed via a Deployment—worker pods only show up at the namespace level. Adding a service (even headless) with the appropriate labels is necessary to see them as a separate “number_of_running_pods” metric. Creating a headless service lets you group them separately.

It recommends creating a "headless" service with `clusterIP: None` so that CloudWatch agent will start reporting service metrics for these pods.

```
apiVersion: v1
kind: Service
metadata:
  name: worker-headless
  namespace: rackname-appname
spec:
  clusterIP: None
  selector:
    app: myapp
    service: worker
  ports:
    - port: 8080
      targetPort: 8080
```

I'm not sure if this is the correct solution, and it seems like a bit of a hack to be honest. But I'd love to have these "ContainerInsights" > "ClusterName, Namespace, Service" metrics available for non-web services as well. Please let me know if there's an easier way to acheive the same goal.

I do have memory/cpu metrics for these pods, but I'm just missing the count metric.
